# docker engine version 19.0.3, so:
# (3.8 not working)
version: '2.2'

services:

  # The postgres service for msfdb
  # built from ordinary postgres image with initial databases msf and msf_test
  msfdb-postgres:
    image: "postgres"
    networks:
      mynet:
        ipv4_address: 172.18.0.2
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_MULTIPLE_DATABASES=msf,msf_test

  # The main kali service, this runs a ssh server inside a kali container
  # containing kali's top10 and other basic networking tools
  # built from dockerfile
  kali:
    build:
      context: .
      dockerfile: kali-dockerfile
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    networks:
      mynet:
        ipv4_address: 172.18.0.3
    devices:
      - "/dev/net/tun"
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    volumes:
      - kali-root:/root
    ports:
      - "222:22"
    command: ["/usr/sbin/sshd", "-D", "-e"]


volumes:
  pgdata:
  kali-root:

# Run on an isolated network seperated from the host
networks:
  mynet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/24
          gateway: 172.18.0.1
