version: "3"

services:
    shellshock:
        image: vulnerables/cve-2014-6271
        networks:
            mynet:
                ipv4_address: 172.18.0.5
        ports:
            - "8080:80"
    #web-dvwa:
    # Damn Vulnerable Web Application
    #    image: vulnerables/web-dvwa
    #    networks:
    #        mynet:
    #            ipv4_address:  172.18.0.4
    #    ports:
    #        - "80:80"

    # The postgres service for msfdb
    # built from ordinary postgres image with initial databases msf and msf_test
    msfdb-postgres:
        image: "postgres"
        networks:
            mynet:
                ipv4_address: 172.18.0.2
        volumes:
            - pgdata:/var/lib/postgresql/data
            - ./copy-files/docker-postgresql-multiple-databases:/docker-entrypoint-initdb.d
            - ./shared:/home/postgres/shared
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_MULTIPLE_DATABASES="msf","msf_test"

    # The main kali service, this runs an ssh server inside the kali container
    # with kali's top10 tools and other basic pentesting tools
    # You can run firefox in this container, GUI will open on the host
    # (if you've configured xhost on the host as specified in readme, 
    # and the Xauthority file is mounted correctly)
    kali:
        build:
            context: .
            dockerfile: kali-dockerfile
        hostname: "${HOSTNAME}"
        sysctls:
            - net.ipv6.conf.all.disable_ipv6=0
        networks:
            mynet:
                ipv4_address: 172.18.0.3
        #network_mode: "host"
        # to allow vpn connection
        devices:
            - "/dev/net/tun"
        cap_add:
            - NET_ADMIN
            - SYS_PTRACE
        # for reverse engineering purposes
        security_opt:
            - seccomp=unconfined
        volumes:
            - ./copy-files/entrypoint_kali.sh:/entrypoint.sh
            - ./copy-files/id_rsa_host.pub:/root/.ssh/client_keys.pub
            - ./copy-files/database.yml:/usr/share/metasploit-framework/config/database.yml
            - ./shared:/root/shared
            - ./writeups:/root/python-writeups
            - /tmp/.X11-unix:/tmp/.X11-unix
            - /run/user/1000/gdm/Xauthority:/root/.Xauthority
            - kali-wd:/root/workdir
        ports:
            - "222:22"
        #command: ["/bin/bash"]
        command: ["/usr/sbin/sshd", "-D", "-e"]
        #command: ["env"]
        entrypoint:
            - /entrypoint.sh
        environment:
            - DISPLAY=${DISPLAY}


volumes:
    pgdata:
    kali-wd:

# Run on an isolated network seperated from the host
networks:
    mynet:
        driver: bridge
        ipam:
            config:
                - subnet: 172.18.0.0/24
