development:
  adapter: postgresql
  database: msf
  username: postgres
  password: postgres
  host: 172.18.0.2
  port: 5432
  pool: 5
  timeout: 5

production:
  adapter: postgresql
  database: msf
  username: postgres
  password: postgres
  host: 172.18.0.2
  port: 5432
  pool: 5
  timeout: 5

test:
  adapter: postgresql
  database: msf_test
  username: postgres
  password: postgres
  host: 172.18.0.2
  port: 5432
  pool: 5
  timeout: 5
